# OneMed Fakturabehandling - Streamlit Configuration
# Optimalisert for OneMed sin profesjonelle helseteknologi-identitet

[theme]
base = "light"  # Standard lys modus (kan endres i appen)
primaryColor = "#497886"  # OneMed EKTE bakgrunnsfarge - ikke junior blå
backgroundColor = "#FAFAFA"  # Profesjonell hvit bakgrunn
secondaryBackgroundColor = "#FFFFFF"  # Hvite kort/overflater
textColor = "#212121"  # Profesjonell mørk tekst
font = "sans serif"  # Clean, professional font

[server]
# Lokalt utviklingsmiljø - perfekt for interne verktøy
headless = false  # Åpner automatisk i nettleser
port = 8501  # Standard Streamlit port
address = "localhost"  # Kun lokal tilgang for sikkerhet

[browser]
gatherUsageStats = false  # Ikke send data til Streamlit
serverAddress = "localhost"
serverPort = 8501

[ui]
hideTopBar = false  # Vis Streamlit-menyen
hideSidebarNav = false  # Vis sidebar-navigasjon

[global]
developmentMode = false  # Produksjonsmodus for stabilitet
dataFrameSerialization = "legacy"  # Kompatibilitet med pandas